/* dbinfunc.c */
extern int Do_ne_1_ss(UINT1 *v1, const UINT1 *v2, size_t n);
extern int Do_ne_1_ns(const UINT1 *v1, UINT1 *v2, size_t n);
extern int Do_eq_1_ss(UINT1 *v1, const UINT1 *v2, size_t n);
extern int Do_eq_1_ns(const UINT1 *v1, UINT1 *v2, size_t n);
extern void Do_ne_4_ss(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_ne_4_ns(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_eq_4_ss(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_eq_4_ns(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_gt_4_ss(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_gt_4_ns(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_gt_4_sn(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_ge_4_ss(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_ge_4_ns(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_ge_4_sn(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_lt_4_ss(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_lt_4_ns(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_lt_4_sn(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_le_4_ss(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_le_4_ns(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_le_4_sn(UINT1 *r, const INT4 *v1, const INT4 *v2, size_t n);
extern void Do_ne_s_ss(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_ne_s_ns(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_eq_s_ss(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_eq_s_ns(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_gt_s_ss(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_gt_s_ns(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_gt_s_sn(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_ge_s_ss(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_ge_s_ns(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_ge_s_sn(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_lt_s_ss(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_lt_s_ns(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_lt_s_sn(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_le_s_ss(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_le_s_ns(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void Do_le_s_sn(UINT1 *r, const REAL4 *v1, const REAL4 *v2, size_t n);
extern void  Do_if_1_ss(UINT1 *r, const UINT1 *test, const UINT1 *val, size_t n);
extern void  Do_if_1_ns(UINT1 *r, const UINT1 *test, const UINT1 *val, size_t n);
extern void  Do_if_1_sn(UINT1 *r, const UINT1 *test, const UINT1 *val, size_t n);
extern void Do_if_4_ss(INT4 *r, const UINT1 *test, const INT4 *val, size_t n);
extern void Do_if_4_ns(INT4 *r, const UINT1 *test, const INT4 *val, size_t n);
extern void Do_if_4_sn(INT4 *r, const UINT1 *test, const INT4 *val, size_t n);
extern void Do_if_s_ss(REAL4 *r, const UINT1 *test, const REAL4 *val, size_t n);
extern void Do_if_s_ns(REAL4 *r, const UINT1 *test, const REAL4 *val, size_t n);
extern void Do_if_s_sn(REAL4 *r, const UINT1 *test, const REAL4 *val, size_t n);
extern void Do_if_else_1_nns(UINT1 *r, const UINT1 *test, const UINT1 *t, const UINT1 *f, size_t n);
extern void Do_if_else_1_nsn(UINT1 *r, const UINT1 *test, const UINT1 *t, const UINT1 *f, size_t n);
extern void Do_if_else_1_nss(UINT1 *r, const UINT1 *test, const UINT1 *t, const UINT1 *f, size_t n);
extern void Do_if_else_1_sss(UINT1 *r, const UINT1 *test, const UINT1 *t, const UINT1 *f, size_t n);
extern void Do_if_else_1_ssn(UINT1 *r, const UINT1 *test, const UINT1 *t, const UINT1 *f, size_t n);
extern void Do_if_else_1_snn(UINT1 *r, const UINT1 *test, const UINT1 *t, const UINT1 *f, size_t n);
extern void Do_if_else_1_sns(UINT1 *r, const UINT1 *test, const UINT1 *t, const UINT1 *f, size_t n);
extern void Do_if_else_4_nss(INT4 *r, const UINT1 *test, const INT4 *t, const INT4 *f, size_t n);
extern void Do_if_else_4_sss(INT4 *r, const UINT1 *test, const INT4 *t, const INT4 *f, size_t n);
extern void Do_if_else_4_ssn(INT4 *r, const UINT1 *test, const INT4 *t, const INT4 *f, size_t n);
extern void Do_if_else_4_snn(INT4 *r, const UINT1 *test, const INT4 *t, const INT4 *f, size_t n);
extern void Do_if_else_4_sns(INT4 *r, const UINT1 *test, const INT4 *t, const INT4 *f, size_t n);
extern void Do_if_else_4_nns(INT4 *r, const UINT1 *test, const INT4 *t, const INT4 *f, size_t n);
extern void Do_if_else_4_nsn(INT4 *r, const UINT1 *test, const INT4 *t, const INT4 *f, size_t n);
extern void Do_if_else_s_nss(REAL4 *r, const UINT1 *test, const REAL4 *t, const REAL4 *f, size_t n);
extern void Do_if_else_s_sss(REAL4 *r, const UINT1 *test, const REAL4 *t, const REAL4 *f, size_t n);
extern void Do_if_else_s_ssn(REAL4 *r, const UINT1 *test, const REAL4 *t, const REAL4 *f, size_t n);
extern void Do_if_else_s_snn(REAL4 *r, const UINT1 *test, const REAL4 *t, const REAL4 *f, size_t n);
extern void Do_if_else_s_sns(REAL4 *r, const UINT1 *test, const REAL4 *t, const REAL4 *f, size_t n);
extern void Do_if_else_s_nns(REAL4 *r, const UINT1 *test, const REAL4 *t, const REAL4 *f, size_t n);
extern void Do_if_else_s_nsn(REAL4 *r, const UINT1 *test, const REAL4 *t, const REAL4 *f, size_t n);
