/* dunfunc.c */
extern void Do_4_2_b(UINT1 *r, const INT4 *v, size_t n);
extern void Do_4to1(UINT1 *r, const INT4 *v, size_t n);
extern void Do_sto1(UINT1 *r, const REAL4 *v, size_t n);
extern void Do_sto4(INT4 *r, const REAL4 *v, size_t n);
extern void Do_s_2_b(UINT1 *r, const REAL4 *v, size_t n);
extern void Do_1_2_4(INT4 *r, const UINT1 *v, size_t n);
extern void Do_s_2_4(INT4 *r, const REAL4 *v, size_t n);
extern void Do_1_2_s(REAL4 *r, const UINT1 *v, size_t n);
extern void Do_4_2_s(REAL4 *r, const INT4 *v, size_t n);
extern void Do_l_2_d(REAL4 *r, const UINT1 *v, size_t n);
extern void Do_1_2_d(REAL4 *r, const UINT1 *v, size_t n);
extern void Do_4_2_d(REAL4 *r, const INT4 *v, size_t n);
extern void Do_4_2_l(UINT1 *r, const INT4 *v, size_t n);
extern void Do_s_2_l(UINT1 *r, const REAL4 *v, size_t n);
extern void Do_d_2_l(UINT1 *r, const REAL4 *v, size_t n);
extern int Do_1_2_b(UINT1 *v, size_t n);
extern int Do_d_2_s(REAL4 *v, size_t n);
extern void Do_downstreamdist(REAL4 *r, const UINT1 *v, size_t n);
extern void Do_pit(INT4 *r, const UINT1 *v, size_t n);
extern void Do_maptotal(REAL4 *r, const REAL4 *v, size_t n);
extern void Do_nodirection(UINT1 *r, const REAL4 *v, size_t n);
extern void Do_mapminimum_4(INT4 *r, const INT4 *v, size_t n);
extern void Do_mapminimum_s(REAL4 *r, const REAL4 *v, size_t n);
extern void Do_mapmaximum_4(INT4 *r, const INT4 *v, size_t n);
extern void Do_mapmaximum_s(REAL4 *r, const REAL4 *v, size_t n);
extern void Do_maparea_1(REAL4 *r, const UINT1 *v, size_t n);
extern void Do_maparea_4(REAL4 *r, const INT4 *v, size_t n);
extern void Do_maparea_s(REAL4 *r, const REAL4 *v, size_t n);
extern int Do_defined_1(UINT1 *v, size_t n);
extern void Do_defined_4(UINT1 *r, const INT4 *v, size_t n);
extern void Do_defined_s(UINT1 *r, const REAL4 *v, size_t n);
extern void Do_normal(REAL4 *r, const UINT1 *v, size_t n);
extern void Do_uniform(REAL4 *r, const UINT1 *v, size_t n);
void Do_normal_1(REAL4 *values, const UINT1 *b, size_t n);
void Do_uniform_1(REAL4 *values, const UINT1 *b, size_t n);

extern int Do_spatial_4(INT4 *vL, INT4 *vR, size_t n);
extern int Do_spatial_1(UINT1 *vL, UINT1 *vR, size_t n);
extern int Do_spatial_s(UINT4 *vL, UINT4 *vR, size_t n);
