/* globfunc.c */
extern int Do_areaaverage(void *out, const void **ins);
extern int Do_areaarea(void *out, const void **ins);
extern int Do_areadiversity(void *out, const void **ins);
extern int Do_areamajority(void *out, const void **ins);
extern int Do_areamaximum(void *out, const void **ins);
extern int Do_areauniform(void *out, const void **ins);
extern int Do_areanormal(void *out, const void **ins);
extern int Do_areaminimum(void *out, const void **ins);
extern int Do_areatotal(void *out, const void **ins);
extern int Do_catchment(void *out, const void **ins);
extern int Do_catchmenttotal(void *out, const void **ins);
extern int Do_subcatchment(void *out, const void **ins);
extern int Do_clump(void *out, const void **ins);
extern int Do_downstream(void *out, const void **ins);
extern int Do_drain(void *out, const void **ins);
extern int Do_ldddist(void *out, const void **ins);
extern int Do_downstreamtotal(void * out, const void **ins);
extern int Do_upstream(void *out, const void **ins);
extern int Do_streamorder(void *out, const void **ins);
extern int Do_transient(void *out, const void **ins);
extern int Do_aspect(void *out, const void **ins);
extern int Do_path(void *out, const void **ins);
extern int Do_slope(void *out, const void **ins);
extern int Do_window4total(void *out, const void **ins);
extern int Do_plancurv(void *out, const void **ins);
extern int Do_profcurv(void *out, const void **ins);
extern int Do_slopelength(void *out, const void **ins);
extern int Do_view(void *out, const void **ins);
extern int Do_extentofview(void *out, const void **ins);
extern int Do_inversedistance(void * out, const void **ins);
extern int Do_windowaverage(void *out, const void **ins);
extern int Do_markwhilesumle(void * out, const void **ins);
extern int Do_markuntilsumge(void * out, const void **ins);
extern int Do_ellipseaverage(void *out, const void **ins);
extern int Do_windowdiversity(void *out, const void **ins);
extern int Do_windowhighpass(void *out, const void **ins);
extern int Do_windowmajority(void *out, const void **ins);
extern int Do_windowmaximum(void *out, const void **ins);
extern int Do_windowminimum(void *out, const void **ins);
extern int Do_windowtotal(void *out, const void **ins);
extern int Do_kinematic(void *out, const void **ins);
extern int Do_order(void *out, const void **ins);
extern int Do_lddmask(void *out, const void **ins);
extern int Do_move(void *out, const void **ins);
extern int Do_shift(void *out, const void **ins);
extern int Do_shift0(void *out, const void **ins);
extern int Do_lddrepair(void *out, const void **ins);
extern int Do_brenner(void *out, const void **ins);
extern int Do_influencesimplegauss(void *out, const void **ins);
extern int Do_distributesimplegauss(void *out, const void **ins);
extern int Do_ibngauss(void *out, const void **ins);
extern int Do_horizontan(void *out, const void **ins);
