namespace calc {
extern int Do_accutraveltime(void *s, void *f, const void **ins);
int Do_accutraveltimefraction(void *s, void *f, const void **ins);
int Do_accutraveltimefractionremoved(void *removed, const void **ins);
extern int Do_spread(void *c, void *z, const void **ins);
extern int Do_spreadmax(void *c, void *z, const void **ins);
extern int Do_spreadldd(void *c, void *z, const void **ins);
extern int Do_lddcreate(void *l, void *d, const void **ins);
extern int Do_lddcreatend(void *l, void *d, const void **ins);

extern int Do_dynamicwave(void *q, void *h, const void **in);
extern int Do_route(void *l, void *d, const void **ins);
extern int Do_diffuse(void *s, void *f, const void **ins);
extern int Do_areaarea(void *out, const void **ins);
extern int Do_areadiversity(void *out, const void **ins);
extern int Do_areamajority(void *out, const void **ins);
extern int Do_areauniform(void *out, const void **ins);
extern int Do_areanormal(void *out, const void **ins);
extern int Do_catchment(void *out, const void **ins);
extern int Do_catchmenttotal(void *out, const void **ins);
extern int Do_subcatchment(void *out, const void **ins);
extern int Do_clump(void *out, const void **ins);
extern int Do_downstream(void *out, const void **ins);
extern int Do_drain(void *out, const void **ins);
extern int Do_ldddist(void *out, const void **ins);
extern int Do_upstream(void *out, const void **ins);
extern int Do_streamorder(void *out, const void **ins);
extern int Do_transient(void *out, const void **ins);
extern int Do_aspect(void *out, const void **ins);
extern int Do_path(void *out, const void **ins);
extern int Do_slope(void *out, const void **ins);
extern int Do_window4total(void *out, const void **ins);
extern int Do_plancurv(void *out, const void **ins);
extern int Do_profcurv(void *out, const void **ins);
extern int Do_slopelength(void *out, const void **ins);
extern int Do_view(void *out, const void **ins);
extern int Do_extentofview(void *out, const void **ins);
extern int Do_inversedistance(void * out, const void **ins);
extern int Do_windowaverage(void *out, const void **ins);
extern int Do_markwhilesumle(void * out, const void **ins);
extern int Do_markwhilesumge(void * out, const void **ins);
extern int Do_ellipseaverage(void *out, const void **ins);
extern int Do_windowdiversity(void *out, const void **ins);
extern int Do_windowhighpass(void *out, const void **ins);
extern int Do_windowmajority(void *out, const void **ins);
extern int Do_windowmaximum(void *out, const void **ins);
extern int Do_windowminimum(void *out, const void **ins);
extern int Do_windowtotal(void *out, const void **ins);
extern int Do_order(void *out, const void **ins);
extern int Do_lddmask(void *out, const void **ins);
extern int Do_move(void *out, const void **ins);
extern int Do_shift(void *out, const void **ins);
extern int Do_shift0(void *out, const void **ins);
extern int Do_lddrepair(void *out, const void **ins);
extern int Do_brenner(void *out, const void **ins);
extern int Do_influencesimplegauss(void *out, const void **ins);
extern int Do_distributesimplegauss(void *out, const void **ins);
extern int Do_ibngauss(void *out, const void **ins);
extern int Do_horizontan(void *out, const void **ins);
extern int Do_riksfraction(void *out, void const** ins);
extern int Do_squarefraction(void *out, void const** ins);
extern int Do_gradx(void* out, void const** ins);
extern int Do_grady(void* out, void const** ins);
extern int Do_divergence(void* out, void const** ins);
extern int Do_diver(void* out, void const** ins);
extern int Do_lax(void* out, void const** ins);
extern int Do_laplacian(void* out, void const** ins);
}
