
set(CMAKE_C_COMPILER gcc-8)
set(CMAKE_CXX_COMPILER g++-8)


include(${CMAKE_CURRENT_LIST_DIR}/gcc.cmake)


set(CMAKE_C_FLAGS_RELEASE
    "${PCR_C_FLAGS} ${PCR_C_FLAGS_GCC7} ${PCR_C_FLAGS_GCC8}"
)

set(CMAKE_CXX_FLAGS_RELEASE
    "${PCR_CXX_FLAGS} ${PCR_CXX_FLAGS_GCC7} ${PCR_CXX_FLAGS_GCC8}"
)
set(CMAKE_C_FLAGS_DEBUG
    "-Wall"
)

set(CMAKE_CXX_FLAGS_DEBUG
    "-Wall"
)
