# Options for selecting the modules to build.
# PCRASTER_BUILD_<module>

# Options for selecting features.
# PCRASTER_WITH_<feature>

option(PCRASTER_BUILD_ALL "Build everything" FALSE)
option(PCRASTER_WITH_ALL "Support all features" FALSE)
option(PCRASTER_BUILD_DOCUMENTATION "Build documentation" FALSE)
option(PCRASTER_BUILD_TEST "Build tests" FALSE)


if(PCRASTER_BUILD_ALL)
    set(PCRASTER_BUILD_DOCUMENTATION TRUE)
    set(PCRASTER_BUILD_TEST TRUE)
endif()


if(PCRASTER_BUILD_DOCUMENTATION)
    set(PCRASTER_DOXYGEN_REQUIRED TRUE)
    set(PCRASTER_TEST_REQUIRED TRUE)
endif()


if(PCRASTER_BUILD_TEST)
    set(PCRASTER_BOOST_REQUIRED TRUE)
    list(APPEND PCRASTER_REQUIRED_BOOST_COMPONENTS
        date_time filesystem math_c99 program_options python regex system
        unit_test_framework)
endif()


set(PCRASTER_CURL_REQUIRED TRUE)
set(PCRASTER_CURSES_REQUIRED TRUE)
set(PCRASTER_GDAL_REQUIRED TRUE)
set(PCRASTER_GEOS_REQUIRED TRUE)
set(PCRASTER_IMAGE_MAGICK_REQUIRED TRUE)
set(PCRASTER_LIB_XML2_REQUIRED TRUE)
set(PCRASTER_LIB_XSLT_REQUIRED TRUE)
set(PCRASTER_LIB_XSLT_XSLTPROC_REQUIRED TRUE)
set(PCRASTER_OPENGL_REQUIRED TRUE)
set(PCRASTER_PCRASTER_RASTER_FORMAT_REQUIRED TRUE)
set(PCRASTER_PYTHON_INTERP_REQUIRED TRUE)
set(PCRASTER_PYTHON_LIBS_REQUIRED TRUE)
set(PCRASTER_QT_REQUIRED TRUE)
set(PCRASTER_QWT_REQUIRED TRUE)
set(PCRASTER_SQLITE_REQUIRED TRUE)
set(PCRASTER_XERCES_REQUIRED TRUE)
set(PCRASTER_XSD_REQUIRED TRUE)
