if(UNIX)
  set(CPACK_PACKAGE_VENDOR "${${PROJECT_NAME}_ORGANISATION_NAME}")
  set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
  set(CPACK_RESOURCE_FILE_README "${PROJECT_SOURCE_DIR}/README.md")

  set(CPACK_SOURCE_GENERATOR TXZ)

  set(CPACK_SOURCE_PACKAGE_FILE_NAME "${PROJECT_NAME}-${${PROJECT_NAME}_VERSION}")

  file(READ ${CMAKE_CURRENT_LIST_DIR}/PCRasterPackagingExclude.cmake _cpack_ignore)
  string(REGEX REPLACE "\n" ";" _cpack_ignore ${_cpack_ignore})
  set(CPACK_SOURCE_IGNORE_FILES "${_cpack_ignore}")

  set(CPACK_PACKAGE_CHECKSUM SHA256)

  include(CPack)

endif()
