{% set version = "0.0.0" %}

package:
  name: pcraster
  version: {{ version }}

source:
  path: ../../../


build:
  number: 0

  ignore_run_exports_from:
    - libboost-devel

  missing_dso_whitelist:
    - C:/Windows/System32/MSVCP140.dll      # [win]
    - C:/Windows/System32/VCRUNTIME140.dll  # [win]
    - C:/Windows/System32/imagehlp.dll      # [win]
    - C:/Windows/System32/GLU32.dll         # [win]
    - C:/Windows/System32/OPENGL32.dll      # [win]
    - C:/Windows/System32/dwmapi.dll        # [win]
    - C:/Windows/System32/WTSAPI32.dll      # [win]
    - Library/bin/MSVCP140.dll              # [win]
    - Library/bin/VCRUNTIME140.dll          # [win]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make                                  # [win]

  host:
    - xorg-libxfixes                        # [linux]
    - libgl-devel                           # [linux]
    - libboost-devel
    - xerces-c
    - qt-main
    - ncurses                               # [not win]
    - libgdal
    - python
    - numpy
    - vs2015_runtime                        # [win]
    - libglu                                # [linux]
    - pybind11-abi
    - pybind11

  run:
    - python
    - libgdal
    - ncurses                               # [not win]
    - vs2015_runtime                        # [win]
    - libglu                                # [linux]

test:
    imports:
       - pcraster
    commands:
        - asc2map
        - col2map
        - legend
        - map2asc
        - map2col
        - mapattr
        - oldcalc
        - pcrcalc
        - resample
        - table

about:
  home: http://www.pcraster.eu
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Environmental modelling software.'
  description: |
    PCRaster is a collection of tools and software libraries tailored to the
    construction of spatio-temporal environmental models. Application domains
    are amongst others hydrology (rainfall-runoff, global water balance,
    groundwater (with Modflow)), ecology, or land use change.
    PCRaster includes a rich set of spatial operations for manipulating and
    analysing raster maps. A Python framework supports Monte Carlo simulations
    and data assimilation (Ensemble Kalman Filter and Particle Filter). The
    Aguila tool allows for the interactive visualisation of stochastic spatio-
    temporal data.
  doc_url: https://pcraster.geo.uu.nl/pcraster/latest/documentation/index.html
  dev_url: https://github.com/pcraster/pcraster


extra:
  recipe-maintainers:
    - OliverSchmitz
