show:
	aguila streamE.map + streamNE.map + streamN.map + streamNW.map + streamSE.map + streamS.map + streamSW.map + streamW.map weightE.map + weightNE.map + weightN.map + weightNW.map + weightSE.map + weightS.map + weightSW.map + weightW.map
