name: Development Linux Conda CI

on:
    push:
    pull_request:

jobs:
    build_linux:

        strategy:
            matrix:
                os: [ubuntu-24.04, macos-15, windows-2025]
            fail-fast: false

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }}

        timeout-minutes: 90

        steps:

            - name: Configure system
              if: runner.os == 'Linux'
              run: |
                  sudo apt update
                  sudo apt install mesa-common-dev libglu1-mesa-dev libegl-dev

            - name: Checkout PCRaster
              uses: actions/checkout@v4

            - uses: conda-incubator/setup-miniconda@v3
              with:
                  miniforge-version: latest
                  auto-update-conda: false
                  conda-remove-defaults: true
                  python-version: 3.13

            - name: Build
              shell: bash -l {0}
              run: |
                  mamba install rattler-build
                  rattler-build build --recipe environment/conda/recipe.yaml
