name: Development Windows

on:
    push:
    pull_request:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                config:
                - {
                      name: "Windows 2022",
                      os: windows-2022,
                      cc: "cl", cxx: "cl",
                      activate_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat",
                      activate_version: "x64 -vcvars_ver=14.2"
                  }
                - {
                      name: "Windows 2025",
                      os: windows-2025,
                      cc: "cl", cxx: "cl",
                      activate_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat",
                      activate_version: "x64 -vcvars_ver=14.4"
                  }

        runs-on: ${{ matrix.config.os }}

        name: ${{ matrix.config.name }}

        timeout-minutes: 75

        steps:

        - name: Create build directory
          run: mkdir build
          shell: cmd

        - name: Checkout PCRaster
          uses: actions/checkout@v4

        - uses: conda-incubator/setup-miniconda@v3
          with:
              miniforge-version: latest
              auto-update-conda: false
              conda-remove-defaults: true
              python-version: 3.13

        - shell: cmd /C call {0}
          run: |
              conda install pybind11 numpy cmake ninja libboost-devel xerces-c libgdal gdal make qt6-main qt6-charts

        - name: Configure PCRaster
          shell: cmd /C call {0}
          run: |
              "${{ matrix.config.activate_script }}" ${{ matrix.config.activate_version }} && ^
              cmake ^
                  -S . ^
                  -B build ^
                  -G"Ninja Multi-Config" ^
                  -D CMAKE_CONFIGURATION_TYPES="Release;Debug" ^
                  -D CMAKE_C_COMPILER=${{ matrix.config.cc }} ^
                  -D CMAKE_CXX_COMPILER=${{ matrix.config.cxx }} ^
                  -D PCRASTER_BUILD_TEST=ON ^
                  -D CMAKE_INSTALL_PREFIX=package ^
                  -D CMAKE_VERBOSE_MAKEFILE=OFF

        - name: Build release
          shell: cmd /C call {0}
          run: |
              "${{ matrix.config.activate_script }}" ${{ matrix.config.activate_version }} && ^
              cmake --build build --config Release --target all

        - name: Install PCRaster
          shell: cmd /C call {0}
          run: |
              "${{ matrix.config.activate_script }}" ${{ matrix.config.activate_version }} && ^
              cmake --install build --config Release

        - name: Test release
          shell: cmd /C call {0}
          run: |
              "${{ matrix.config.activate_script }}" ${{ matrix.config.activate_version }} && ^
              ctest --test-dir build --output-on-failure --build-config Release
