name: Development Conda

on:
    push:
    pull_request:

jobs:
    build:

        strategy:
            matrix:
                include:
                  - os: windows-2025
                    target-platform: win-64

            fail-fast: false

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }}

        timeout-minutes: 90

        steps:

            - name: Checkout PCRaster
              uses: actions/checkout@v4

            - name: Build
              uses: prefix-dev/rattler-build-action@v0.2.33
              with:
                  artifact-name: package-${{ matrix.target-platform }}
                  upload-artifact: false
                  recipe-path: environment/conda/recipe.yaml
