name: Development Conda

on:
    push:
    pull_request:

jobs:
    build:

        strategy:
            matrix:
                include:
                  - os: ubuntu-24.04
                    target-platform: linux-64
                  - os: ubuntu-24.04-arm
                    target-platform: linux-aarch64
                  - os: macos-15
                    target-platform: osx-arm64
                  - os: windows-2025
                    target-platform: win-64

            fail-fast: false

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }}

        timeout-minutes: 90

        steps:

            - name: Checkout PCRaster
              uses: actions/checkout@v4

            - uses: mamba-org/setup-micromamba@v2
              with:
                environment-name: pcrbuild
                create-args: >-
                  rattler-build
                init-shell: >-
                  bash
                  powershell

            - name: Build
              run: |
                  rattler-build build --recipe environment/conda/recipe.yaml