name: Development Conda

on:
    push:
    pull_request:

jobs:
    build:

        strategy:
            matrix:
                include:
                  - os: windows-2025
                    target-platform: win-64

            fail-fast: false

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }}

        timeout-minutes: 90

        steps:

            - name: Checkout PCRaster
              uses: actions/checkout@v4

            - uses: conda-incubator/setup-miniconda@v3
              with:
                  miniforge-version: latest
                  auto-update-conda: false
                  conda-remove-defaults: true
                  python-version: 3.13

            - name: Build
              if: runner.os == 'Linux' || runner.os == 'macOS'
              shell: bash -el {0}
              run: |
                  mamba install rattler-build
                  rattler-build build --recipe environment/conda/recipe.yaml

            - name: Build
              if: runner.os == 'Windows'
              shell: cmd /C call {0}
              run: |
                  mamba activate test
                  mamba install rattler-build
                  rattler-build build --recipe environment/conda/recipe.yaml
