name: Linux Conda CI

on: [push]

jobs:
    build:

        strategy:
            matrix:
                include:
                  - os: ubuntu-24.04
                    target-platform: linux-64
                  - os: macos-15
                    target-platform: osx-arm64
                  - os: macos-15-intel
                    target-platform: osx-64
                  - os: windows-2025
                    target-platform: win-64

            fail-fast: false

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }}

        timeout-minutes: 120

        steps:

        - name: Checkout PCRaster
          uses: actions/checkout@v6

        - uses: conda-incubator/setup-miniconda@v3
          with:
              miniforge-version: latest
              auto-update-conda: false
              conda-remove-defaults: true

        - shell: bash -l {0}
          run: |
              mamba install boa -c conda-forge

        - name: Build
          shell: bash -l {0}
          run: |
              boa build environment/configuration/receipe
