name: Release branch Linux


on:
    schedule:
      - cron:  '45 3 2 * *'

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-22.04]
                compiler:
                    - { cc: gcc-13, cxx: g++-13 }
            fail-fast: false

        runs-on: ${{ matrix.os }}

        timeout-minutes: 90

        steps:

        - name: Checkout PCRaster
          uses: actions/checkout@v4
          with:
              ref: 4.4

        - name: Configure system
          run: |
              sudo apt update
              sudo apt install ${{ matrix.compiler.cc }} ninja-build gdal-bin libgdal-dev libxerces-c-dev libxml2-dev libxslt1-dev libboost-dev libboost-date-time-dev libboost-filesystem-dev libboost-test-dev libboost-timer-dev libncurses5-dev libxml2 libxml2-utils mesa-common-dev libglu1-mesa-dev libgl1-mesa-glx python3 libpython3-dev python3-numpy python3-psutil qtbase5-dev libqt5charts5-dev libqt5opengl5-dev cmake pybind11-dev
              # Only required for documentation:
              sudo apt install python3-sphinx doxygen python3-matplotlib graphviz

        - name: Configure PCRaster
          shell: bash -l {0}
          run: |
              mkdir build
              cmake \
                  -S . \
                  -B build \
                  -G"Ninja Multi-Config" \
                  -D CMAKE_CONFIGURATION_TYPES="Release;Debug" \
                  -D CMAKE_C_COMPILER=${{ matrix.compiler.cc }} \
                  -D CMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
                  -D PCRASTER_BUILD_TEST=ON \
                  -D PCRASTER_BUILD_DOCUMENTATION=ON \
                  -D PCRASTER_WITH_FLAGS_IPO=OFF \
                  -D Python3_EXECUTABLE:FILEPATH=/usr/bin/python3 \
                  -D CMAKE_INSTALL_PREFIX=package

        - name: Build release
          shell: bash
          run: |
              cmake --build build --config Release --target all

        - name: Install PCRaster
          shell: bash
          run: |
              cmake --install build --config Release

        - name: Create source package
          shell: bash
          run: |
              cmake --build build --config Release --target package_source

        - name: Test release
          env:
              LOGNAME: pcrtester
          shell: bash
          run: |
              ctest --test-dir build --output-on-failure --build-config Release
